### ISSUE TITLE
UI showing while in Shift+P (Camera) mode

### ISSUE THREAD

**Issue by MCCZik** [Redon-Tech/radio-system#2]
Hi, I'd like if you could disable the GUI in some way. Like when you use Shift+P (for photoshooting), the GUI is too big.

**Comment by parker02311** [comment]
Hi, technically this issue is both a bug and enhancement, I will be fixing the bug and adding the enhancement in the next version.

**Comment by parker02311** [comment]
Fixed by 6a895019b09fbfc5c106303d48cf45e39f03f992
