### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by MCCZik** [Redon-Tech/radio-system#3]
When sending a message in chat, it also displays in radio but twice. Please fix quickly. (It is necessary for my game, and it is launching tommorow at 17:00 CET.

**Comment by parker02311** [comment]
Hello @MCCZik, first, thank you for creating the bug report via GitHub, please be patient with us, I make these for free and do not have a ton of time to work on them so if I can't fix the bug by tomorrow I apologize. 

More importantly, are you using LegacyChatService or TextChatService (if you can not tell please just send a screenshot of what your chat input bar looks like), as I do believe their is a Roblox bug within a LegacyChatService event causing messages to duplicate.

**Comment by MCCZik** [comment]
> Hello @MCCZik, first, thank you for creating the bug report via GitHub, please be patient with us, I make these for free and do not have a ton of time to work on them so if I can't fix the bug by tomorrow I apologize. 
> 
> More importantly, are you using LegacyChatService or TextChatService (if you can not tell please just send a screenshot of what your chat input bar looks like), as I do believe their is a Roblox bug within a LegacyChatService event causing messages to duplicate.

Yes, I have the Legacy version of chat. Is there a way to prevent this issue? Thanks a lot!

**Comment by parker02311** [comment]
Could you try out using TextChatService instead and let me know if the issue continues? I believe this is related to [this](https://devforum.roblox.com/t/chatted-randomly-firing-twice-in-public-experiences-only/2732978) bug report that appears to still be an issue. 

I will make a workaround for it if it is, but in the mean time if TextChatService fixes it I would just stick with that.

**Comment by MCCZik** [comment]
> Could you try out using TextChatService instead and let me know if the issue continues? I believe this is related to [this](https://devforum.roblox.com/t/chatted-randomly-firing-twice-in-public-experiences-only/2732978) bug report that appears to still be an issue. 
> 
> I will make a workaround for it if it is, but in the mean time if TextChatService fixes it I would just stick with that.

Will this change affect somehow how chat was used in Legacy version?

**Comment by parker02311** [comment]
No, unless you use `Player.Chatted` in any of your scripts using TextChatService won't cause any issues. If you don't want to change you will likely have to wait till later today or late tomorrow for me to finish a patch and release it.

**Comment by MCCZik** [comment]
Okay, thank you very much. I will wait, and if the time hurries up, then I will quickly put the normal textchat version. Thanks for helping!
